### PR TITLE
Create Welsh lang strings.xml

### PR DESCRIPTION
**Pull request by Cymrodor**

### CODE REVIEW

**Comment by schildbach** [comment]
Thanks for your contribution! Note that translations happen on Transifex, see https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.md#translations

Since Welsh has just been added as a language on Transifex, I can upload your translation to there and add you as a language moderator. If you agree, please state your Transifex user name.

**Comment by Cymrodor** [comment]
It's me that's done all the translation on Transifex. This is the translation file from there.

**Comment by schildbach** [comment]
Ok then I'll pull from there.

Btw. I've seen a few occurences of the word "Fitcoin". Is this intentional?

**Comment by Cymrodor** [comment]
Thanks. Yes. It's a mutation that occurs in Welsh.

**Comment by schildbach** [comment]
I imported your localization from Transifex and made you a coordinator of that language. I hope that's ok with you.

Unfortunately Google Play doesn't support Welsh, so I can't upload your market descriptions for now. But the strings in the app should show from version 7.22 on.

Do Welsh mutations also apply to (foreign) names? Just wondering about Fitcoin because there is an altcoin named like this. Could be confusing.

**Comment by schildbach** [comment]
I'm closing this as it's merged now.

**Comment by joungakim** [comment]
블록탐색기에서  피어.블럭이 모두 표시가되는데  지갑에 도달할수없었다   오늘이유를 알아냈다  나는 대한민국이다 피어에  포르투칼 피어번호가 저장됐다    이미 나타난 탐색에 나라변경은 어떻게하는지  알고싶다

In the block explorer, all the peers and blocks are displayed but I could not reach my wallet. I found out why. I am a Korean. I have a Portuguese peer number stored in my peers.

**Pull request closed without merging**
