### PR TITLE
Patch 1 - added badges

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Comment by schildbach** [comment]
See https://github.com/bitcoin-wallet/bitcoin-wallet/commit/c16bda142134b8b93294fec9f62dbda146828f38.

**Comment by PanderMusubi** [comment]
@schildbach In that commit links have been added, but not the actual badges. That is fixed with this PR. Is that okay?

**Comment by schildbach** [comment]
Yes, but I think we don't need the badges themselves. And the way they are linked from F-Droid and Google Play, we'd be leaking the users privacy to these websites.

**Comment by PanderMusubi** [comment]
Understandable. FYI, hosting the F-Droid badge yourself is not a problem.

**Pull request closed without merging**
