### PR TITLE
Change the ripple effect on action buttons

### PR DESCRIPTION
**Pull request by ademar111190**
Please, check the https://github.com/bitcoin-wallet/bitcoin-wallet/pull/577 for more Context.

I did create a new style for wallet action buttons, it was useful to set the ripple effect as well as to centralize the theming there.

### CODE REVIEW

**Comment by schildbach** [comment]
I did some more tests. If you turn the device sideways the standard actions become actions with text. And they use the same small-circle effect as the one you're trying to eliminate.

By coincence, I tested the app on Android 5.x and I think the circle effect is looking best there, regardless of if the actions are icon+text or just icon. Maybe we can just copy the style from there?

Anyway, please don't close issues just because you make changes to your branch. Just amend or append your commits, and use force-push if you need. Using a separate PR per change creates unmaintainable clutter.

**Comment by schildbach** [comment]
I cherry-picked the part of your PR that extracts some style attributes into a style.xml style, but for now I'm using the existing ActionButton style so that it can apply to all action buttons at the same time.

Regarding your ripple effect suggestion, I think it is usually applied to the foreground rather than the background, because background is typically used elsewhere already.

**Comment by ademar111190** [comment]
I see.
Another problem is the ripple effect changes from a version to another...
I'm thinking in a way to maintain the effect consistently across the scenarios and android versions.

**Comment by ademar111190** [comment]
Sorry I lost track of this PR; I'm closing it as it no longer makes sense today

**Pull request closed without merging**
