### PR TITLE
Add badges for F-Droid and Google Play

### PR DESCRIPTION
**Pull request by fyfyone**
I added F-Droid and Play store badges to the README.md as requested in [#409](https://github.com/bitcoin-wallet/bitcoin-wallet/issues/409).

### CODE REVIEW

**Comment by schildbach** [comment]
This implementation leaks private data to Google and Fdroid, just by visiting our github repo with the web browser. Are we allowed (by license) to include the button images into our repo itself?

**Comment by fyfyone** [comment]
I couldn't find anything on the [Google Play badges](https://play.google.com/intl/en_us/badges/) site, so I have submitted an inquiry to [this](https://support.google.com/googleplay/contact/brand_developer) form, they said it will take a few days.

F-Droid logo is licenced under a CC BY-SA licence:
> The F-Droid logo was created by William Theaker. Updates to that, and additional artwork, are by Robert Martinez. All are dual licensed under CC-BY-SA 3.0 Unported or GPLv3+.

So I guess we can clone it into the repo.

**Comment by schildbach** [comment]
We could also just skip badges and only provide links into the stores.

**Comment by schildbach** [comment]
I rewrote the PR a bit and merged. Thanks!

**Pull request closed without merging**
