### PR TITLE
One nicer word added

### PR DESCRIPTION
**Pull request by sandakersmann**
I think "Close" would fit better in this context.

### CODE REVIEW

**Comment by schildbach** [comment]
What's bad about "dismiss"?

**Comment by sandakersmann** [comment]
When you open for example the safety notes, you have to press "Dismiss" to close/exit the notes. "Dismiss" sound like a function you can press if you don't want to follow the notes, while "Close" would sound better if you just would like to close down the notes.

**Comment by JoaoGFarias** [comment]
I guess the button name should be changed as well, if so this PR to be accepted.

**Comment by zacheryj** [comment]
Not to sure of the requests anyone able to help explain it in easier terms.

**Comment by kasperwiese8** [comment]
access

**Comment by kasperwiese8** [comment]
weite acces

**Comment by Pinus95** [comment]
Which url I put in

**Pull request closed without merging**
