### PR TITLE
compileable for most recent Android Studio 3

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by schildbach** [comment]
Thanks for your contribution. We decided against gradle wrapper as this adds a binary into our repository. Also, the build target is Ubuntu 16.04 LTS (maybe 18.04 LTS in 6 months), so currently we're at Gradle 2.10.

**Comment by hannesa2** [comment]
And what's about to have right version in app, I wrote something in PlayStore that's not really serious. 
You fixed something without a commit in github !
That's why it more then serious to have git sha1 and git commit count in versionName

**Comment by hannesa2** [comment]
Where is the last fix 5.38 ?
image

**Comment by hannesa2** [comment]
concerning to have a git without Gradle: I guess I can't change your decision, so I have to accept it. But I personally see no reason to work always with two years old stuff. -just my two cents-

ALL companies where I worked with Android since the last seven years, have no fear about Gradle in git, and they were some really big and important companies where security was an first place and having Fraunhofer Institute on board for security advisory

**Comment by hannesa2** [comment]
I see you pushed from an other remote now to github
image
That means your build you PlayStore version from an other repo **(wtf)**, that's why the commit count  and sha1 is most important for anyone who what build up trust in this wallet.

I accept your gradle decision, but here is my last question:
Make it sense to split this PR into apply git info to versionName and Gradle/lib update ? (means a realistic chance to be merged or should I go my own ways ?)

**Comment by schildbach** [comment]
Generally it makes sense to split different ideas into different PRs. I would rather not change the versioning scheme however. I see the point of using the git commit hash, but wouldn't it be enough to use it in the output filename and/or for display in the app (e.g. about screen)? What purpose does the git commit count serve?

**Comment by hannesa2** [comment]
We speak here about trust, not more not less.

I look for a way, how to trust in this app. I saw some **not** trustfull behavior in this thread, probably you trust in Ubuntu Gradle more, but I'm not, I do not see it. (Only you see what to be used).
If you do not trust the Gradle, I commited, then you can easily verify and copy same Gradle from your local machine to this PR and the diff should be not measurable. Same for me, when you theoretical update Gradle.

Concerning version info:
I see there is version info manually done. Bad
When you do an automatism with git sha1, I can every time verify, if version from PlayStore is the same in github. version count is just a nice mechanism to increase versionnumber, then nothing must no more changed manually.
Both combined (git count and git sha1) makes it more complicated to fake, but not impossible.
Of course it should be shown in "about"

If you agree, I make a PR, otherwise I close this topic

**Comment by mm88mm** [comment]
I don't know why it's saying it's my app because I did not make this app
and I I do not condone this out but I don't I don't even know what f******
app you're talking about

**Comment by hannesa2** [comment]
I see no interest in more transparency, 
no singe answer about trust increment ... the story smells

You'll laugh and shrug your shoulders ... I'm out

**Pull request closed without merging**
