### PR TITLE
Add satoshi denomination in wallet

### PR DESCRIPTION
**Pull request by AbelLykens**
Not sure if the attached commit already is enough, but having a Satoshi display/denomination would be great!

There is no discussion on what a Satoshi is.

Especially for Lighting users, Satoshi display could be useful.

Thanks for your consideration.

### CODE REVIEW

**Comment by schildbach** [comment]
You'll need to add at least the English label for `@string/preferences_precision_labels_0_8`.

**Comment by schildbach** [comment]
At various places in the app we'll need to show the currency code "sat" rather than "BTC", "mBTC" or "µBTC". Also, at some places currency symbols are used. Currently, bitcoinj's MonetaryFormat class is used for these codes/symbols.

**Comment by AbelLykens** [comment]
Not sure where to continue. Where would I set this label? I edited `wallet/res/values/values.xml`. 
In `wallet/res/values/strings.xml` I do not see text values for the strings.

Do I understand correctly that I:
1) Need to find where "sat" would be set in the code/translations? If so, a hint would be helpful.
2) Might have to to a PR on bitcoinj for this denomination?

**Comment by schildbach** [comment]
Look for existing `preferences_precision_labels` in `strings.xml` and add your new label to that.

Indeed, a PR to bitcoinj's `MonetaryFormat` would be useful.

**Comment by AbelLykens** [comment]
Made [edits](https://github.com/bitcoin-wallet/bitcoin-wallet/pull/594/commits/c5c290775ae2e48d6e814f27b9a5c24634d2f387), appears to be added to this PR [?].

Also made [PR](https://github.com/bitcoinj/bitcoinj/pull/1947) in bitcoinj

**Comment by pppp388** [comment]
38CvHfGoz29LfGVwJJ4nUU8rHX7UDZq3oe

**Comment by pppp388** [comment]
38CvHfGoz29LfGVwJJ4nUU8rHX7UDZq3oe

**Comment by AbelLykens** [comment]
I got a bit stuck on this. Not sure what my next steps should be.

**Comment by guardian939** [comment]
c5c290775ae2e48d6e814f27b9a5c24634d2f387

**Comment by AliAli215** [comment]
Ok

بتاريخ الاثنين، 17 أغسطس 2020، جاء من guardian939 <notifications@github.com

**Review by rude9 — APPROVED** [review]

**Review by Aleksey0329 — COMMENTED** [review]
wallet/res/values/strings.xml

**Comment by Aleksey0329** [comment]
Як це працює?

**Review by cebi1992 — APPROVED** [review]

**Comment by kzu** [comment]
:shipit:

**Review by Vangoga75 — APPROVED** [review]

**Review by Vangoga75 — APPROVED** [review]

**Comment by Vangoga75** [comment]
Bez kādiem vārdiem

**Review by Vangoga75 — APPROVED** [review]

**Comment by Vangoga75** [comment]
Ir ok laikam

**Review by Wrathcoin — APPROVED** [review]

**Review by Wahhe1 — COMMENTED** [review]
C

**Review by Wrathcoin — CHANGES_REQUESTED** [review]
Aight then

**Review by mohammadpourzaker — APPROVED** [review]

**Review by Lynnfunestas — APPROVED** [review]

**Review by Lynnfunestas — APPROVED** [review]

**Comment by Lynnfunestas** [comment]
Not yet

**Comment by Dorineb07** [comment]
Ok

Op zo 19 sep. 2021 13:29 schreef Lynnfunestas ***@***.***>:

**Review by berzaza27 — APPROVED** [review]

**Review by JaymenArciniega — APPROVED** [review]

**Comment by romara20** [comment]
Thanks

**Review by Kiler91daw — APPROVED** [review]

**Comment by schildbach** [comment]
This has been implemented via 87f817e63ebc00cac0f2af77367b54cf6f9442f7.

**Pull request closed without merging**
