### PR TITLE
Bless

### PR DESCRIPTION
**Pull request by rude9**

### CODE REVIEW

**Comment by rude9** [comment]
Changed

**Comment by schildbach** [comment]
Is there a specific problem you want to solve with this?

**Comment by rude9** [comment]
Yes I have been trying to get my blockchain coins but address is unparsed 0
and mostly 404 error shows no need to get it before Nov thanks for the
reply Bro u are  gem .
---------- Forwarded message ----------

**Comment by schildbach** [comment]
I beg your pardon?

**Comment by rude9** [comment]
Sorry brother all i was trying say m
having problems syncing my wallet

**Comment by schildbach** [comment]
Use Options > Report issue to report your issue.

**Comment by schildbach** [comment]
Duplicate of #457.

**Comment by schildbach** [comment]
Duplicate of #457

**Pull request closed without merging**
