### PR TITLE
gradle / AndroidStudio integration

### PR DESCRIPTION
**Pull request by devrandom**
This does the following:

* Gradle build files
* Test and prod configurations in one source tree
* Uses BuildConfig (supersedes the use of package name)

### CODE REVIEW

**Comment by artvel** [comment]
here is a clean gradle / AndroidStudio Project based on schildbachs bitcoin-wallet just without sample-integration-android
https://github.com/artvel/bitcoin_wallet

**Comment by schildbach** [comment]
I finally did migrate the project to Gradle. Sorry for not using your PR. I found a plugin for the SVG conversion and helped a bit to fix the last bugs. Next step is use build flavors for testnet vs. mainnet and Direct Download vs. Google Play vs. BlackBerry.

**Comment by schildbach** [comment]
Note I'm still on Eclipse. Android Studio is still way too slow on my machine, probably because I'm using OpenJDK.

**Comment by schildbach** [comment]
Closing this, as the project migrated to gradle.

**Pull request closed without merging**
