### PR TITLE
Convert all 3 README(s) to Markdown

### PR DESCRIPTION
**Pull request by jonathancross**
Added links for Electrum, Bitcoin Core, fixed some typos and formatted as Markdown.
We can also keep `README.recovery` and just include a note saying:
"See README.recovery.md".

Thoughts?

### CODE REVIEW

**Comment by schildbach** [comment]
Generally I like this, thanks! I would prefer the content changes (links, typos) to be separated into separate commits though. Also if README.recovery is markdown, README should probably be too?

**Comment by schildbach** [comment]
Also I need to think about broken links -- I referenced the file quite often.

**Comment by jonathancross** [comment]
Sure, makes sense.  I created #393 with only the text changes / improvements.
We can close this and consider the switch to Markdown later (with the other README files, etc).

**Comment by jonathancross** [comment]
Hi @schildbach , where should we go from here now that  #393 is merged and conflicts resolved?

* Should I convert the other README into Markdown?
* Are you satisfied with "**_See README.recovery.md_**" in the old README or is there a better way to redirect users to the new file?

**Comment by jonathancross** [comment]
Hi @schildbach, I've rebased and simplified this PR so it is just a file rename.  This [looks surprisingly good](https://github.com/jonathancross/bitcoin-wallet/blob/912d2db55b08c8b51de3c93ecda24cb43939d003/wallet/README.recover.md) as formatting was already similar to markdown.

**Comment by kitsuphat** [comment]
/I do not know how to say good with bitcoincore because of the time I used
to know how to do and do not know how to contact me. And now, I will tell
you, I do not have the right to return here at home, I called the intention
not to, because there are no reports of coins. Or, even if the email
address registered for the system is clear, but not notified. Another
notice is that you are not entitled to a coin in your pocket.

กิจสุพัฒน์

เมื่อ 11 มิ.ย. 2017 20:33 "Jonathan Cross" <notifications@github.com>
เขียนว่า

**Comment by schildbach** [comment]
Do we really need to add that .md extension, or is there some other way to tell this file is markdown?

The problem is external links to this file, it was mentioned quite often in forums, stackexchange and so on.

**Comment by jonathancross** [comment]
The `.md` extension is how GitHub knows to render as Markdown, I don't think there is a way to indicate filetype without modifying the file extension.

I looked into file redirect / symlinks, but did not find anything that seemed like it would work here.

What do you think about just having "_See README.recovery.md_" inside `README.recovery` so people know to just look for the new file name?

**Comment by schildbach** [comment]
Yes, that'll do. I propose we convert all three READMEs in one go. And actually convert them to markdown (use the features), not just rename them. Just no content changes please, those should go to separate PRs.

**Comment by jonathancross** [comment]
Sounds good.
I've updated this so that it is just 3 clean rename opperations.
As you can see by the previews, they all look perfectly fine with no changes.
I'd recommend we merge this, then I'll immediately add additional Markdown formatting so you can see the diffs (GitHub will get confused if we rename and modify in a single PR).

Adding the  "_See README.recovery.md_" will also be easier once this is merged (if that is what you want?).

**Comment by Sovereignity** [comment]
Hello Andreas, I know we have spoken before about his question I'm going to ask you, however that was a few years ago.
So just in case things have changed. How would I go about creating a bitcoin wallet for personal use?

Any advise or help would be great thanks

Sent from my iPhone

On 16 Jun 2017, at 11:09, Andreas Schildbach <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, that'll do. I propose we convert all three READMEs in one go. And actually convert them to markdown (use the features), not just rename them. Just no content changes please, those should go to separate PRs.

**Comment by schildbach** [comment]
Merged, thanks! Feel free to PR the actual Markdown conversion.

**Pull request closed without merging**
