### PR TITLE
.gitlab-ci.yml: Set up GitLab CI.

### PR DESCRIPTION
**Pull request by schildbach**

### CODE REVIEW

**Comment by msgilligan** [comment]
Looks good to me!

**Comment by msgilligan** [comment]
Are you going to update this with the matrix that includes JDK 11?

**Comment by schildbach** [comment]
> Are you going to update this with the matrix that includes JDK 11?

There is a future PR coming up that will add the matrix and JDK 11.

**Comment by schildbach** [comment]
Thanks for your review! Merged.

**Pull request merged**
